export { Orb, OrbThemeProvider, defineOrbTheme, orbThemeCssVariable } from './components/Orb'
export type {
  OrbAdapter,
  OrbProps,
  OrbSignal,
  OrbSignalListener,
  OrbSlotAttributes,
  OrbSlotName,
  OrbSlotProps,
  OrbState,
  OrbStyle,
  OrbTheme,
  OrbThemeComponent,
  OrbThemeComponentContext,
  OrbThemeComponents,
  OrbThemeConfig,
  OrbThemeCssSection,
  OrbThemeDefaults,
  OrbThemeName,
  OrbThemePreset,
  OrbThemeProviderProps,
  OrbThemeRenderer,
  OrbThemeRendererControlProps,
  OrbThemeRendererProps,
  OrbThemeRendererRootProps,
  BarsAppearance,
  BarsGeometry,
  BarsMotion,
  BarsThemeConfig,
  CircleAppearance,
  CircleGeometry,
  CircleMotion,
  CircleThemeConfig,
  CloudAppearance,
  CloudGeometry,
  CloudMotion,
  CloudThemeConfig,
  DebugAppearance,
  DebugGeometry,
  DebugMotion,
  DebugThemeConfig,
  RadialAppearance,
  RadialGeometry,
  RadialMotion,
  RadialThemeConfig,
} from './components/Orb'

// Backwards-compat aliases (deprecated — use Orb / OrbProps instead)
export { Orb as VoiceOrb } from './components/Orb'
export type { OrbProps as VoiceOrbProps } from './components/Orb'
